name: Deploy to Github Pages

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
env:
  DEPLOY_BASE_URL: ${{ vars.DEPLOY_BASE_URL}}
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.github-pages.output.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install project dependencies
        run: npm install --legacy-peer-deps
      - name: Build the page for deployment
        run: npm run build
      - name: Ensure 404 fallback
        run: cp ./dist/index.html ./dist/404.html
      - name: Configure Github Pages
        uses: actions/configure-pages@v5
      - name: Upload compiled assets to Github Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: Publish Github Pages
        uses: actions/deploy-pages@v4
